Input scene: 	/var/www/data/00b1783c-0639-4aab-84ac-cc1269c0a571/opensfm/undistorted/reconstruction.nvm
Input mesh: 	/var/www/data/00b1783c-0639-4aab-84ac-cc1269c0a571/odm_meshing/odm_mesh.ply
Output prefix: 	/var/www/data/00b1783c-0639-4aab-84ac-cc1269c0a571/odm_texturing/odm_textured_model_geo
Datacost file: 	
Labeling file: 	
Data term: 	gmi
Smoothness term: 	potts
Outlier removal method: 	gauss_clamping
Tone mapping: 	none
Apply global seam leveling: 	True
Apply local seam leveling: 	True
